export type ContentType = "TEXT" | "URL" | "FILE";

export interface MockUser {
  id: string;
  name: string;
  email: string;
  image: string | null;
  isPro: boolean;
}

export interface MockItemType {
  id: string;
  name: string;
  icon: string; 
  color: string; 
  isSystem: boolean;
}

export interface MockItem {
  id: string;
  title: string;
  description: string | null;
  contentType: ContentType;
  content: string | null;
  url: string | null;
  fileUrl: string | null;
  language: string | null;
  itemTypeId: string;
  collectionIds: string[];
  isFavorite: boolean;
  isPinned: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface MockCollection {
  id: string;
  name: string;
  description: string | null;
  isFavorite: boolean;
  defaultTypeId: string | null;
  updatedAt: string;
}

export const currentUser: MockUser = {
  id: "user-1",
  name: "Demo User",
  email: "demouser@example.com",
  image: null,
  isPro: false,
};

export const itemTypes: MockItemType[] = [
  { id: "type-snippet", name: "snippet", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type-prompt", name: "prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type-command", name: "command", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type-note", name: "note", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type-link", name: "link", icon: "Link", color: "#10b981", isSystem: true },
  { id: "type-file", name: "file", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type-image", name: "image", icon: "Image", color: "#ec4899", isSystem: true },
];

export const collections: MockCollection[] = [
  {
    id: "col-react-patterns",
    name: "React Patterns",
    description: "Reusable hooks, render patterns and component recipes.",
    isFavorite: true,
    defaultTypeId: "type-snippet",
    updatedAt: "2026-07-25T13:00:00.000Z",
  },
  {
    id: "col-ai-prompt-library",
    name: "AI Prompt Library",
    description: "System prompts, agents and prompt-engineering experiments.",
    isFavorite: true,
    defaultTypeId: "type-prompt",
    updatedAt: "2026-07-25T10:00:00.000Z",
  },
  {
    id: "col-shell-cli",
    name: "Shell & CLI",
    description: "Daily-driver terminal commands and shell one-liners.",
    isFavorite: false,
    defaultTypeId: "type-command",
    updatedAt: "2026-07-24T15:00:00.000Z",
  },
  {
    id: "col-reading-list",
    name: "Reading List",
    description: "Articles, docs and references worth coming back to.",
    isFavorite: false,
    defaultTypeId: "type-link",
    updatedAt: "2026-07-23T09:00:00.000Z",
  },
  {
    id: "col-interview-prep",
    name: "Interview Prep",
    description: "Notes, DSA snippets and system-design write-ups.",
    isFavorite: true,
    defaultTypeId: "type-note",
    updatedAt: "2026-07-22T09:00:00.000Z",
  },
  {
    id: "col-context-files",
    name: "Context Files",
    description: "Uploaded briefs and specs to feed into models.",
    isFavorite: false,
    defaultTypeId: "type-file",
    updatedAt: "2026-07-21T09:00:00.000Z",
  },
  {
    id: "col-python-snippets",
    name: "Python Snippets",
    description: "Data wrangling, scripts and small utilities.",
    isFavorite: false,
    defaultTypeId: "type-snippet",
    updatedAt: "2026-07-19T09:00:00.000Z",
  },
  {
    id: "col-design-refs",
    name: "Design Refs",
    description: "Screenshots and UI inspiration for later.",
    isFavorite: false,
    defaultTypeId: "type-image",
    updatedAt: "2026-07-18T09:00:00.000Z",
  },
];

export const items: MockItem[] = [
  {
    id: "item-1",
    title: "useDebounce hook",
    description: "Debounce a fast-changing value for search inputs.",
    contentType: "TEXT",
    content: "export function useDebounce<T>(value: T, delay = 300) { /* ... */ }",
    url: null,
    fileUrl: null,
    language: "typescript",
    itemTypeId: "type-snippet",
    collectionIds: ["col-react-patterns"],
    isFavorite: true,
    isPinned: true,
    createdAt: "2026-07-01T09:00:00.000Z",
    updatedAt: "2026-07-25T13:00:00.000Z",
  },
  {
    id: "item-2",
    title: "Compound component pattern",
    description: "Sharing implicit state between related components.",
    contentType: "TEXT",
    content: "const Tabs = ({ children }) => { /* ... */ }",
    url: null,
    fileUrl: null,
    language: "tsx",
    itemTypeId: "type-snippet",
    collectionIds: ["col-react-patterns"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-07-02T09:00:00.000Z",
    updatedAt: "2026-07-20T09:00:00.000Z",
  },
  {
    id: "item-3",
    title: "React Patterns reading notes",
    description: "Notes on render props vs hooks trade-offs.",
    contentType: "TEXT",
    content: "## Render props\n\n...",
    url: null,
    fileUrl: null,
    language: null,
    itemTypeId: "type-note",
    collectionIds: ["col-react-patterns"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-07-03T09:00:00.000Z",
    updatedAt: "2026-07-18T09:00:00.000Z",
  },
  {
    id: "item-4",
    title: "React docs — Thinking in React",
    description: null,
    contentType: "URL",
    content: null,
    url: "https://react.dev/learn/thinking-in-react",
    fileUrl: null,
    language: null,
    itemTypeId: "type-link",
    collectionIds: ["col-react-patterns"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-07-04T09:00:00.000Z",
    updatedAt: "2026-07-15T09:00:00.000Z",
  },
  {
    id: "item-5",
    title: "Code reviewer system prompt",
    description: "Strict, security-focused code review persona.",
    contentType: "TEXT",
    content: "You are a senior engineer reviewing a pull request...",
    url: null,
    fileUrl: null,
    language: null,
    itemTypeId: "type-prompt",
    collectionIds: ["col-ai-prompt-library"],
    isFavorite: true,
    isPinned: false,
    createdAt: "2026-06-20T09:00:00.000Z",
    updatedAt: "2026-07-25T10:00:00.000Z",
  },
  {
    id: "item-6",
    title: "Commit message generator prompt",
    description: "Turns a diff into a conventional commit message.",
    contentType: "TEXT",
    content: "Given the following git diff, write a conventional commit message...",
    url: null,
    fileUrl: null,
    language: null,
    itemTypeId: "type-prompt",
    collectionIds: ["col-ai-prompt-library"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-06-22T09:00:00.000Z",
    updatedAt: "2026-07-10T09:00:00.000Z",
  },
  {
    id: "item-7",
    title: "Prompt-engineering agent notes",
    description: "What worked and didn't when chaining agent prompts.",
    contentType: "TEXT",
    content: "## Findings\n\n...",
    url: null,
    fileUrl: null,
    language: null,
    itemTypeId: "type-note",
    collectionIds: ["col-ai-prompt-library"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-06-25T09:00:00.000Z",
    updatedAt: "2026-07-05T09:00:00.000Z",
  },
  {
    id: "item-8",
    title: "Find and kill process on port",
    description: null,
    contentType: "TEXT",
    content: "lsof -ti tcp:3000 | xargs kill -9",
    url: null,
    fileUrl: null,
    language: "bash",
    itemTypeId: "type-command",
    collectionIds: ["col-shell-cli"],
    isFavorite: true,
    isPinned: true,
    createdAt: "2026-05-10T09:00:00.000Z",
    updatedAt: "2026-07-24T15:00:00.000Z",
  },
  {
    id: "item-9",
    title: "Prune local git branches",
    description: "Removes local branches already merged into main.",
    contentType: "TEXT",
    content: "git branch --merged main | grep -v 'main' | xargs git branch -d",
    url: null,
    fileUrl: null,
    language: "bash",
    itemTypeId: "type-command",
    collectionIds: ["col-shell-cli"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-05-12T09:00:00.000Z",
    updatedAt: "2026-07-12T09:00:00.000Z",
  },
  {
    id: "item-10",
    title: "Dotfiles setup notes",
    description: null,
    contentType: "TEXT",
    content: "## Shell setup\n\n...",
    url: null,
    fileUrl: null,
    language: null,
    itemTypeId: "type-note",
    collectionIds: ["col-shell-cli"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-05-15T09:00:00.000Z",
    updatedAt: "2026-06-30T09:00:00.000Z",
  },
  {
    id: "item-11",
    title: "A Philosophy of Software Design — notes",
    description: null,
    contentType: "URL",
    content: null,
    url: "https://web.stanford.edu/~ouster/cgi-bin/book.php",
    fileUrl: null,
    language: null,
    itemTypeId: "type-link",
    collectionIds: ["col-reading-list"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-04-01T09:00:00.000Z",
    updatedAt: "2026-07-23T09:00:00.000Z",
  },
  {
    id: "item-12",
    title: "Neon serverless Postgres docs",
    description: null,
    contentType: "URL",
    content: null,
    url: "https://neon.tech/docs",
    fileUrl: null,
    language: null,
    itemTypeId: "type-link",
    collectionIds: ["col-reading-list"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-04-02T09:00:00.000Z",
    updatedAt: "2026-07-11T09:00:00.000Z",
  },
  {
    id: "item-13",
    title: "UI inspiration — Linear dashboard",
    description: null,
    contentType: "FILE",
    content: null,
    url: null,
    fileUrl: "https://mock-r2.example.com/linear-dashboard.png",
    language: null,
    itemTypeId: "type-image",
    collectionIds: ["col-reading-list", "col-design-refs"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-04-05T09:00:00.000Z",
    updatedAt: "2026-06-15T09:00:00.000Z",
  },
  {
    id: "item-14",
    title: "Two Sum",
    description: "Classic hash map approach, O(n) time.",
    contentType: "TEXT",
    content: "function twoSum(nums, target) { /* ... */ }",
    url: null,
    fileUrl: null,
    language: "javascript",
    itemTypeId: "type-snippet",
    collectionIds: ["col-interview-prep"],
    isFavorite: true,
    isPinned: false,
    createdAt: "2026-03-01T09:00:00.000Z",
    updatedAt: "2026-07-22T09:00:00.000Z",
  },
  {
    id: "item-15",
    title: "System design — URL shortener",
    description: "Write-up covering hashing, storage and rate limiting.",
    contentType: "TEXT",
    content: "## Requirements\n\n...",
    url: null,
    fileUrl: null,
    language: null,
    itemTypeId: "type-note",
    collectionIds: ["col-interview-prep"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-03-05T09:00:00.000Z",
    updatedAt: "2026-06-28T09:00:00.000Z",
  },
  {
    id: "item-16",
    title: "Behavioral interview answers",
    description: null,
    contentType: "URL",
    content: null,
    url: "https://www.example.com/behavioral-interview-guide",
    fileUrl: null,
    language: null,
    itemTypeId: "type-link",
    collectionIds: ["col-interview-prep"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-03-10T09:00:00.000Z",
    updatedAt: "2026-06-10T09:00:00.000Z",
  },
  {
    id: "item-17",
    title: "Q3 product brief.pdf",
    description: null,
    contentType: "FILE",
    content: null,
    url: null,
    fileUrl: "https://mock-r2.example.com/q3-product-brief.pdf",
    language: null,
    itemTypeId: "type-file",
    collectionIds: ["col-context-files"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-02-01T09:00:00.000Z",
    updatedAt: "2026-07-21T09:00:00.000Z",
  },
  {
    id: "item-18",
    title: "API spec — payments service.md",
    description: null,
    contentType: "FILE",
    content: null,
    url: null,
    fileUrl: "https://mock-r2.example.com/payments-api-spec.md",
    language: null,
    itemTypeId: "type-file",
    collectionIds: ["col-context-files"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-02-05T09:00:00.000Z",
    updatedAt: "2026-06-01T09:00:00.000Z",
  },
  {
    id: "item-19",
    title: "Pandas groupby cheatsheet",
    description: null,
    contentType: "TEXT",
    content: "df.groupby('col').agg({'value': 'sum'})",
    url: null,
    fileUrl: null,
    language: "python",
    itemTypeId: "type-snippet",
    collectionIds: ["col-python-snippets"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-01-10T09:00:00.000Z",
    updatedAt: "2026-07-19T09:00:00.000Z",
  },
  {
    id: "item-20",
    title: "Run linter on staged files",
    description: null,
    contentType: "TEXT",
    content: "git diff --cached --name-only | xargs ruff check",
    url: null,
    fileUrl: null,
    language: "bash",
    itemTypeId: "type-command",
    collectionIds: ["col-python-snippets"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-01-12T09:00:00.000Z",
    updatedAt: "2026-05-20T09:00:00.000Z",
  },
  {
    id: "item-21",
    title: "Dashboard card layout inspiration",
    description: null,
    contentType: "FILE",
    content: null,
    url: null,
    fileUrl: "https://mock-r2.example.com/dashboard-card-layout.png",
    language: null,
    itemTypeId: "type-image",
    collectionIds: ["col-design-refs"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-01-15T09:00:00.000Z",
    updatedAt: "2026-07-18T09:00:00.000Z",
  },
  {
    id: "item-22",
    title: "Raycast command palette reference",
    description: null,
    contentType: "URL",
    content: null,
    url: "https://www.raycast.com",
    fileUrl: null,
    language: null,
    itemTypeId: "type-link",
    collectionIds: ["col-design-refs"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-01-18T09:00:00.000Z",
    updatedAt: "2026-04-30T09:00:00.000Z",
  },
];
